apiVersion: workspace.jupyter.org/v1alpha1
kind: Workspace
metadata:
  name: bgrv-app
  namespace: default
spec:
  displayName: "Gaurav's Notebook"
  image: uv
  desiredStatus: Running
  accessStrategy:
    name: sample-access-strategy
    namespace: default
  accessType: Public 
  ownershipType: Public
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "0.5"
      memory: "1Gi"
